# Generated by Django 2.2 on 2021-06-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufactur', '0002_auto_20210604_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='t_number',
            field=models.PositiveIntegerField(default='1', verbose_name='Табельный номер'),
        ),
    ]
