# Generated by Django 2.2 on 2021-07-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField(db_index=True, verbose_name='Номер партии')),
                ('slug', models.SlugField(max_length=10)),
                ('plastic', models.CharField(choices=[('ВВГ', 'ВВГ'), ('ППГ', 'ППГ')], max_length=3, verbose_name='Пластик')),
                ('design', models.CharField(choices=[('нг', 'нг'), ('Пнг', 'Пнг')], max_length=3, verbose_name='Исполнение')),
                ('purpose', models.CharField(choices=[('LS', 'LS'), ('LTx', 'LTx'), ('FRLS', 'FRLS'), ('FRLSLTx', 'FRLSLTx')], max_length=7, verbose_name='Назначение')),
                ('cores', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Количество жил')),
                ('crosssection', models.IntegerField(choices=[(0.5, 0.5), (0.75, 0.75), (1.0, 1.0), (1.5, 1.5), (2.5, 2.5), (4.0, 4.0), (6.0, 6.0), (10, 10)], verbose_name='Поперечное сечение')),
                ('footage', models.IntegerField(default=15000, verbose_name='Метраж')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('completion', models.DateTimeField(verbose_name='Дата завершения')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('finished', models.BooleanField(default=False, verbose_name='Готов')),
                ('discard', models.BooleanField(default=False, verbose_name='Брак')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Заказы', to='orders.Operation')),
            ],
            options={
                'ordering': ('batch_number',),
                'index_together': {('batch_number', 'slug')},
            },
        ),
    ]
