# Generated by Django 2.2 on 2022-05-22 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Тех операция',
                'verbose_name_plural': 'Тех операции',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField(db_index=True, unique=True, verbose_name='Номер партии')),
                ('slug', models.SlugField(max_length=10)),
                ('plastic', models.CharField(choices=[('ВВГ', 'ВВГ'), ('ППГ', 'ППГ')], default='ВВГ', max_length=3, verbose_name='Пластик')),
                ('design', models.CharField(choices=[('нг', 'нг'), ('Пнг', 'Пнг')], default='нг', max_length=3, verbose_name='Исполнение')),
                ('purpose', models.CharField(choices=[('LS', 'LS'), ('LTx', 'LTx'), ('FRLS', 'FRLS'), ('FRLSLTx', 'FRLSLTx')], default='LS', max_length=7, verbose_name='Назначение')),
                ('cores', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Количество жил')),
                ('crosssection', models.CharField(choices=[('0.5', '0.5'), ('0.75', '0.75'), ('1.0', '1.0'), ('1.5', '1.5'), ('2.5', '2.5'), ('4.0', '4.0'), ('6.0', '6.0'), ('10', '10')], max_length=3, verbose_name='Поперечное сечение')),
                ('footage', models.IntegerField(default=15000, verbose_name='Метраж')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('completion', models.DateField(verbose_name='Дата завершения')),
                ('updated', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('finished', models.BooleanField(db_index=True, default=False, verbose_name='Готов')),
                ('discard', models.BooleanField(db_index=True, default=False, verbose_name='Брак')),
                ('in_production', models.BooleanField(db_index=True, default=False, verbose_name='В производстве')),
                ('operation', models.ForeignKey(default='Грубое волочение', on_delete=django.db.models.deletion.CASCADE, related_name='order_operation', to='orders.Operation', verbose_name='Операция')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('operation', 'batch_number'),
                'index_together': {('batch_number', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductionOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_tara', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('comment', models.CharField(max_length=200, verbose_name='Комментарий')),
                ('finished', models.BooleanField(db_index=True, default=False, verbose_name='Готов')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production', to='orders.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заказ в производство',
                'verbose_name_plural': 'Заказы в производство',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_cores', models.CharField(choices=[('бел', 'белый'), ('син', 'синий'), ('крс', 'красный'), ('чер', 'черный'), ('ж/з', 'жел-зелен'), ('б/ц', 'нет')], default='нет', max_length=3, verbose_name='Цвет жилы')),
                ('container', models.CharField(choices=[('ж/б', 'ж/б'), ('д/б', 'д/б'), ('бух', 'бухта')], default='ж/б', max_length=3, verbose_name='Тара')),
                ('number_container', models.PositiveSmallIntegerField(verbose_name='Номер тары')),
                ('total_in_meters', models.PositiveSmallIntegerField(verbose_name='Метраж')),
                ('date_finished', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('iteration', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('otk', models.BooleanField(db_index=True, default=False)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.Operation', verbose_name='Операция')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log', to='orders.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Log операции',
                'verbose_name_plural': 'Лог операций',
                'ordering': ('date_finished',),
            },
        ),
    ]
