# Generated by Django 2.2 on 2021-07-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='crosssection',
            field=models.CharField(choices=[('0.5', '0.5'), ('0.75', '0.75'), ('1.0', '1.0'), ('1.5', '1.5'), ('2.5', '2.5'), ('4.0', '4.0'), ('6.0', '6.0'), ('10', '10')], max_length=3, verbose_name='Поперечное сечение'),
        ),
    ]
