# Generated by Django 2.2 on 2021-07-14 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210708_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'Тех операция', 'verbose_name_plural': 'Тех операции'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('operation', 'batch_number'), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='design',
            field=models.CharField(choices=[('нг', 'нг'), ('Пнг', 'Пнг')], default='нг', max_length=3, verbose_name='Исполнение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='operation',
            field=models.ForeignKey(default='Грубое волочение', on_delete=django.db.models.deletion.CASCADE, related_name='order_operation', to='orders.Operation', verbose_name='Операция'),
        ),
        migrations.AlterField(
            model_name='order',
            name='plastic',
            field=models.CharField(choices=[('ВВГ', 'ВВГ'), ('ППГ', 'ППГ')], default='ВВГ', max_length=3, verbose_name='Пластик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purpose',
            field=models.CharField(choices=[('LS', 'LS'), ('LTx', 'LTx'), ('FRLS', 'FRLS'), ('FRLSLTx', 'FRLSLTx')], default='LS', max_length=7, verbose_name='Назначение'),
        ),
        migrations.CreateModel(
            name='ProductionOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='Комментарий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production', to='orders.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заказ в производство',
                'verbose_name_plural': 'Заказы в производство',
                'ordering': ('order',),
            },
        ),
    ]
