# Generated by Django 2.2 on 2021-12-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210831_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderlog',
            options={'ordering': ('date_finished',), 'verbose_name': 'Log операции', 'verbose_name_plural': 'Лог операций'},
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='color_cores',
            field=models.CharField(choices=[('бел', 'белый'), ('син', 'синий'), ('крс', 'красный'), ('чер', 'черный'), ('ж/з', 'жел-зелен'), ('б/ц', 'нет')], default='нет', max_length=3, verbose_name='Цвет жилы'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='container',
            field=models.CharField(choices=[('ж/б', 'ж/б'), ('д/б', 'д/б'), ('бух', 'бухта')], default='ж/б', max_length=3, verbose_name='Тара'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='date_finished',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='total_in_meters',
            field=models.PositiveSmallIntegerField(verbose_name='Метраж'),
        ),
    ]
