# Generated by Django 2.2 on 2021-12-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20211223_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completion',
            field=models.DateField(verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='date_finished',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
