# Generated by Django 2.2 on 2021-12-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20211223_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completion',
            field=models.DateTimeField(verbose_name='Дата завершения'),
        ),
    ]
