# Generated by Django 2.2 on 2021-12-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20211223_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completion',
            field=models.DateField(verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
